// Generated by CoffeeScript 1.9.1
(function() {
  var FacebookStrategy, express, passport, router;

  express = require('express');

  router = express.Router();

  passport = require('passport');

  FacebookStrategy = require('passport-facebook').Strategy;

  router.get('/facebook', passport.authenticate('facebook'));

  router.get('/facebook/callback', passport.authenticate('facebook', {
    successRedirect: '/1',
    failureRedirect: '/'
  }));

  module.exports = router;

}).call(this);
