// Generated by CoffeeScript 1.9.1
(function() {
  var express, router;

  express = require('express');

  router = express.Router();


  /* GET home page. */

  router.get('/', function(req, res) {
    res.render('index', {
      title: 'Front Page'
    });
  });

  module.exports = router;

  router.get('/:step', function(req, res) {
    var step;
    step = req.params.step;
    if (step === "1") {
      res.render('step1', {
        title: 'Step ' + step.toString()
      });
    }
    if (step === "2") {
      res.render('step2', {
        title: 'Step ' + step.toString()
      });
    }
    if (step === "3") {
      return res.render('step3', {
        title: 'Step ' + step.toString()
      });
    }
  });

}).call(this);
