// Generated by CoffeeScript 1.9.1
(function() {
  var express, router;

  express = require('express');

  router = express.Router();


  /* GET home page. */

  router.get('/', function(req, res) {
    res.render('index', {
      title: 'Front Page'
    });
  });

  module.exports = router;

  router.get('/:step', function(req, res) {
    var step;
    step = req.params.step;
    return res.render('index', {
      title: 'Step page' + step.toString()
    });
  });

}).call(this);
