// Generated by CoffeeScript 1.9.1
(function() {
  var express, router;

  express = require('express');

  router = express.Router();


  /* GET users listing. */

  router.get('/', function(req, res) {
    res.send('respond with a resource');
  });

  module.exports = router;

}).call(this);
